### ISSUE TITLE
[Question] Update internal Media Controller

### ISSUE THREAD

**Issue by jasperf** [ivenms/laravel-media-manager-for-v9#1]
Found your fork and we are working on integrating it in a new Laravel 9 setup. For our own internal `app/Http/Controllers/Editor/MediaController.php` with additional custom code we have

```php
...
$this->storageDisk = app('filesystem')->disk($this->fileSystem);
$this->storageDisk->getAdapter()->setPathPrefix(public_path('/uploads/'.$this->currentProject->id));
$this->storageDiskInfo = app('config')->get("filesystems.disks.{$this->fileSystem}");
$this->baseUrl = url('/uploads/'.$this->currentProject->id);
$this->db = app('db')
            ->connection($config['database_connection'])
            ->table($config['table_locked']);

$this->storageDisk->addPlugin(new ListWith());
..
```

(only part loaded but we use your namespaces already)

Looking at your `vendor/ivenms/laravel-media-manager/src/App/Controllers/MediaController.php` we can drop the plugin of course and we should. But how can we load media from the path including `public_path('/uploads/'.$this->currentProject->id)` (project path)?

**Comment by ivenms** [comment]
Sorry Jasper, I missed this question completely. I created the fork to support one of my project. The original library now have updates. Please check the https://github.com/ctf0/Laravel-Media-Manager.
